services:
  app: 
    build: #ビルドコンテキストの設定
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src/:/app #ホストのsrcディレクトリをコンテナの/appにバインドマウント

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8080:80 #ホストの8080ポートをコンテナの80ポートにマッピング
    depends_on:
      - app #webサービスはappサービスに依存
    volumes:
      - ./src/:/app #ホストのsrcディレクトリをコンテナの/appにバインドマウント

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306 #ホストの3306ポートをコンテナの3306ポートにマッピング
    environment:
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
