services:
  app:
    build:
      #ビルドコンテキストの設定
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src/:/app #ホストのsrcディレクトリをコンテナの/appにバインドマウント

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 80:80 #ホストの80ポートをコンテナの80ポートにマッピング
      - 443:443
    depends_on:
      - app #webサービスはappサービスに依存
    volumes:
      - ./src/:/app #ホストのsrcディレクトリをコンテナの/appにバインドマウント
      - certs-data:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306 #ホストの3306ポートをコンテナの3306ポートにマッピング
    environment:
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql

  certbot:
    image: certbot/certbot
    volumes:
      - certs-data:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
      - ./docker/certbot/run-certbot.sh:/opt/run-certbot.sh
    entrypoint: "/bin/sh /opt/run-certbot.sh"

volumes:
  mysql-volume:
  certs-data:
  certbot-webroot:
