services:
  app:
    build:
      #ビルドコンテキストの設定
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        - APP_ENV=${APP_ENV:-local}
    volumes:
      - ./src/1/:/app #ホストのsrcディレクトリをコンテナの/appにバインドマウント

  # TODO: Web1とWeb2のコンテナを分けてポートも分ける（Web1のプロキシからWeb2のポートにアクセスするように）
  web1:
    build:
      context: .
      dockerfile: ./docker/web1/Dockerfile
    ports:
      - 80:80 #ホストの80ポートをコンテナの80ポートにマッピング
      - 443:443
    depends_on:
      - app #webサービスはappサービスに依存
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - ./src/1/:/app #ホストのsrcディレクトリをコンテナの/appにバインドマウント
      - certs-data:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot

  web2:
    # プロキシ先専用
    build:
      context: .
      dockerfile: ./docker/web2/Dockerfile
    depends_on:
      - app #webサービスはappサービスに依存
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - ./src/2/:/app #ホストのsrcディレクトリをコンテナの/appにバインドマウント

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306 #ホストの3306ポートをコンテナの3306ポートにマッピング
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    volumes:
      - mysql-volume:/var/lib/mysql

  certbot:
    image: certbot/certbot
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - certs-data:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
      - ./docker/certbot/run-certbot.sh:/opt/run-certbot.sh
    entrypoint: "/bin/sh /opt/run-certbot.sh"

volumes:
  mysql-volume:
  certs-data:
  certbot-webroot:
